services:
  server:
    build:
      context: .
      args:
        SERVER_NAME: board
    container_name: "${PROJECT_NAME}-server"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .config.json:/var/www/html/.config.json
      - ./docker/apache/boards.conf:/etc/apache2/sites-available/boards.conf
      - ./docker/logs/error.log:/var/log/apache2/error.log
      - ./docker/logs/access.log:/var/log/apache2/other_vhosts_access.log
      - ./docker/logs/debug.txt:/var/www/html/debug.txt
      - ./docker/php/board.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/volumes/cache:/var/www/html/cache:rw
      - ./docker/volumes/demos:/var/www/html/demos:rw
      - ./docker/volumes/sessions:/var/www/html/sessions:rw
